# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Machine Learning - Lee & Oh & Lee
tagline:             'A Jekyll theme'
description:         '머신 러닝 공부 자료 정리'
url:                 https://smallorbig.github.io/ml_lol
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Semin Oh
  url:               
  email:             osmfirst@gmail.com

# Custom vars
version:             1.0.0
