# coding: utf-8
# Site settings
# title:          Tale
title: Machine Learning - Lee & Oh & Lee
# description:    "Minimal Jekyll theme for storytellers"
description:    "기계학습 공부 및 정리"
# baseurl:        "/tale"
baseurl:        "/ml_lol"
# url:            "https://chesterhow.github.io"
url:            "https://smallorbig.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Semin Oh
  url:          https://smallorbig.github.io
  email:        osmfirst@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
